### ISSUE TITLE
Create views or materialized views.

### ISSUE THREAD

**Issue by merqurio** [bitnine-oss/agensgraph#303]
I've tried to create a (materialized) view from the a Cypher query but it seems it's not possible yet. Have you thought about it ? It would be a nice way to cache some expensive queries.

```sql
CREATE MATERIALIZED VIEW test_view AS
     MATCH (a:smthng)-[r:owned_by*..5]->(b {id: 195967001})
```

**Comment by gtyun** [comment]
That idea is interesting.
Before implementing this idea, I think we need to review table architecture which has graph typed column and AgensGraph's grammar. 
Because of our own roadmap, scheduling is needed to implement additional feature.
That's why your interesting idea can not be made immediately.
Thank you for your suggestion.

**Comment by gtyun** [comment]
I expected this 'graph view' would be easily possible. Because we already has graph type, so table with graph typed column is possible. But view of postgresql is strongly related with SQL. So it seems a little difficult.
If you interested in why, you can reference this link. https://www.postgresql.org/docs/10/static/rules-views.html
