### ISSUE TITLE
Function `id(n)`

### ISSUE THREAD

**Issue by slayer** [bitnine-oss/agensgraph#310]
Hi

`id(node)` works fine for `RETURN`, but fails for `WHERE`

```
agraph=# MATCH (p:Person) WHERE id(p) = '3.445391' RETURN id(p);
ERROR:  42883: operator does not exist: graphid = jsonb
LINE 1: MATCH (p:Person) WHERE id(p) = '3.445391' RETURN id(p);
                                     ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
LOCATION:  op_error, parse_oper.c:726

agraph=# MATCH (p:Person) WHERE id(p) = '3.445391'::graphid RETURN id(p);
ERROR:  42601: syntax error at or near "::"
LINE 1: MATCH (p:Person) WHERE id(p) = '3.445391'::graphid RETURN id...
                                                 ^
LOCATION:  scanner_yyerror, scan.l:1127


```

What type of syntax do I need ?

**Comment by yeonchun** [comment]
You can do it as follows.
match (p:Person) WHERE to_jsonb( id(p) ) = '3.445391' RETURN id(p);

**Comment by bravius** [comment]
@yeonchun - But then the query has to do a Seq Scan instead of the much faster Index Scan.  To get around this cast to graphid (using a hybrid query) and this will preserve the Index Scan.

MATCH (p:Person) WHERE id(p) = ((SELECT '3.445391'::graphid)) RETURN id(p);;

**Comment by slayer** [comment]
I think it's worth adding support for syntax 
`MATCH (p:Person) WHERE id(p) = '3.445391'::graphid`

or even 
`MATCH (p:Person) WHERE id(p) = 4453911` because `3.` points to `Person` label

**Comment by bravius** [comment]
I think the idea with v1.3 was to eliminate the need for :: type conversion syntax, by making jsonb the base type.

But in this one case, a lookup on a graphid requires type conversion, which means full table scan instead of index scan.  I notice a huge hit on query performance when using to_jsonb(id()) on big sets

Since the :: cast syntax seems to be gone from v1.3 Cypher mode, one option would be a to_graphid() function:

MATCH (p:Person) 
WHERE id(p) = to_graphid('3.445391') 
RETURN id(p);

The comparison operators would have to work for arrays of type graphid as well, for the sake if the IN operator.

MATCH (p:Person) 
WHERE id(p) IN [to_graphid('3.445391'),to_graphid('3.445392'),...] 
RETURN id(p);

**Comment by protodef** [comment]
@bravius - I'll work on making use of index for `expr IN [scalar, scalar, ...]` case. I was only thinking about literal values but, as you mentioned, `graphid` also have to be considered. Thank you for letting me know.

**Comment by emotionbug** [comment]
Closes old issues.
