### ISSUE TITLE
Graphs are not restored properly after backup/restore database with pg_dump/pg_restore commands

### ISSUE THREAD

**Issue by OksanaProtsyk** [bitnine-oss/agensgraph#371]
Hi,
I am trying to backup/restore AgensGraph db using pg_dump/pg_restore utilities (as I understood from manual it should work for both relational and graph entities). However, it fails when I try to backup/restore Graphs( it works well when I restoring tables (RDB entities)).
Below are 2 cases that are failed.
The first one:
	Create some Database (eg. testDB) 
	1. Create Graph with some data. (eg. testgraph) 
	2. Perform backup (using "pg_dump -U agens -Fc testDB > testDB.dump" command) 
	3. Drop created Graph from testDB.
	4. Perform restore from backup ("pg_restore -U agens  -d testDB testDB.dump" command)
	ER: Graph testDB exist, you can query data from it).
	AR: Only tables with graph data exist, it is not possible to set testDB as graph_path and graph list is empty in restored db. Seems that graph is restored as a relational schema instead of graph.

The second one: 
	Create some Database (eg. testDB) 
	1. Create Graph with some data. (eg. testgraph) 
	2. Perform backup (I am using "pg_dump -U agens -Fc testDB > testDB.dump" command) 
	3. Perform restore from backup ("pg_restore -U agens  -d testDB testDB.dump" command)
	ER: Graph testDB exist and contains distinct data created in the beginning.
	AR: Graph testDB exist, however all data is duplicated.

Seems it is not possible to properly backup/restore graphs using discussed utilities. Could you please suggest the proper way for backuping/restoring db with graphs? Or investigate and fix the issue with pg_dump/pg_restore utilities?

Thanks,
Oksana

**Comment by gtyun** [comment]
Hello, Oksana

For the first case,
Do you using AgensGraph 1.3.1 ? 
I tested dump & restore just now and it works.

Could you check the path of the pg_dump binary? The pg_dump must be binary file of AgensGraph, not PostgreSQL. Because we modified pg_dump to work well with graph data.
Actually graph data shares the structure of relational schema so it could be dumped by 'original' pg_dump as the relational tables.
If it was correct pg_dump within the AgensGraph, it is critical problem and I will investigate it more.
So please let me know.


And the second case, I think it is normal. Or.. I did not understand what is you expected result.
If it was creating new data from dump file, see option of pg_restore 
`  -c, --clean                  clean (drop) database objects before recreating`
Otherwise, please explain again. 

Thanks.

**Comment by OksanaProtsyk** [comment]
Hello, Yun,
Seems that you are right. The problem was in incorrect path to pg_dump binary. It used Postgre one instead of Agens by default. With correct binary it works. 
Thanks for the response.
