### ISSUE TITLE
Why change from Apache to Affero GPL?  This is a problem

### ISSUE THREAD

**Issue by pratikpparikh** [bitnine-oss/agensgraph#439]
Dear owners (@gtyun , @htlim, and others), 

Why change from Apache.  This will be a problem for a lot of organization.  Most organization ban AGPL software.  I urge you to rethink this decision,  I have been using it Agensgraph now, and I liked the fact that it was apache.  I understand the need to monetize but AGPL is toxic.  I will give you an example, I contributed the PR #384 which I think is needed for my program to run.  Just the fact that you now made it AGPL, I can't run with this modification as you have not accepted my PR.  This is just one example of the problem.  Please keep it Apache, it makes sure that community can use it and not be afraid of the project owners coming after them unfairly.  There are other ways to monetize, take the timescale (https://github.com/timescale/timescaledb) for instance.

Experts usually recommend the following "Stay as far away from AGPL as you possibly can — nothing good can come from using it." from the article https://thebetterstory.co/the-saas-developers-uber-short-guide-to-using-open-source-projects-f32511fe118d

I trust your intentions are good but this is not good for the community to push your contribution to realize its applications.  Lots of IP governance in companies turn down the component as soon as they see **\*GPL\*** in the license.  It is a bad word for most organizations.

I request you to look for alternatives?  Hope rest of the community will urge the same.

Regards,
Pratik Parikh

**Comment by johnberzy-bazinga** [comment]
@pratikpparikh, I 100% agree. This licensing change will definitely scare off a lot of potential adopters. Please reconsider.

Regards,
John

**Comment by merqurio** [comment]
In deed will make us fork the project or look for an alternative. Please
reconsider.

Regards,

**Comment by pratikpparikh** [comment]
@merqurio @johnberzy-bazinga I am willing to support a fork if you all have the time to contribute.  Ideally, I would not want to do that as I want to support bitnine in being successful but this change leaves us no option.  I urge the owners to rethink, they are on right track and we as communicate can help them move in the correct direction.

**Comment by gtyun** [comment]
I have no authority to decide the license but this issue has been reported on the top line. 
They are discussing and I'm waiting the results too.

**Comment by pratikpparikh** [comment]
@gtyum thank you please consider there are a lot of problems that AGPL brings additionally at this stage changing a license is probably a problem for agens in general.  Please keep us in the loop.

**Comment by pratikpparikh** [comment]
@abevoelker not to say this change is unethical on so many different levels.  I find hard to believe this can stand given that so many from the community have helped and addressed the issues for agensgraph they would do everyone a favor if they go back to apache and extend the version with value-add services or modules that can bundle it for enterprise distribution.  Everyone does it, they can do it too without screwing the community.

**Comment by abevoelker** [comment]
@pratikpparikh I just happened to find this project in the last couple days as I've been looking into graph databases, so I don't know anything about the project to make those kinds of judgments myself. Although it looks like in terms of code contribution (not reported issues), it's been all Bitnine employees, save for one guy tweaking some install instructions: https://github.com/bitnine-oss/agensgraph/graphs/contributors So they may not feel like they're missing out on much by relicensing.

I thought it was an interesting project because I was independently wondering how far you could get modeling a graph database in Postgres using a table for vertices and one for edges, with a JSONB column on each for vertex/edge attributes, and if I understand the docs correctly that seems like what AgensGraph is doing at a basic level.

Anyway, although the AGPL does reflexively trigger some worry, it may not be as bad as you might think. [MongoDB for example is AGPL-licensed](https://www.mongodb.com/blog/post/the-agpl), yet that doesn't trigger the AGPL for web apps that use it. Mongo's reasoning for that is because they've licensed their drivers under the Apache license. Unfortunately Bitnine also relicensed their JDBC, Python, Go, etc. drivers under AGPL so that scenario doesn't apply here - I think you'd have to write your own non-AGPL driver to airgap your apps against AGPL virality. But that's simpler than having to fork and maintain a whole different database implementation. (Note: I'm not a lawyer and none of the above is legal advice)

**Comment by pratikpparikh** [comment]
@abevoelker fair points but in my opinion this is unethical at many levels.  Yes writing a driver is trivial.  Great points, but what you miss is all the pull request that people have contributed too.  I know for a fact there are people outside the contribution list that have committed to the current codebase.

**Comment by ITwrx** [comment]
i am not associated with this project. the following is just the reality of the situation and a rebuttal to an issue post that i consider subversive to the proper licensing of this project and in turn, free humanity.

> Most organization ban AGPL software.

Only Slaveware peddlers should be afraid to use the AGPL.

> Experts usually recommend the following "Stay as far away from AGPL as you possibly can

experts? yeah, ok. SAAS (Slaveware As A Service) application vendors who fear justice can't incorporate software that protects users' freedoms in it's license. No kidding...That's kind of the whole point of the AGPL.

> Please keep it Apache, it makes sure that community can use it and not be afraid of the project owners coming after them unfairly.

Permissive(lesser) Free Software licenses allow parasites and would-be Straw Bosses to enjoy _their_ software freedoms and use Free Software without having to give back to the Free Software Community, or respect their software users' freedoms. Unfortunately for the world, this seems to be the most important draw for many advocates of these licenses, as evidenced by this issue.

Furthermore, nobody ever goes after the "community" for "using" GPL software. That's a blatant mischaracterization.  "Unfairly"? They could theoretically go after **GPL violators**, but the Free Software Community rarely even goes after the most egregious ones. 

The fact is, no _freedom respecting_ organization using AGPL software within the _clear_ requirements of the license has any reason to fear, and anyone suggesting otherwise is spewing FUD.

agensgraph, please continue to stand for user freedoms by keeping the license AGPL, no matter how loud the transparent clamoring gets.

**Comment by pratikpparikh** [comment]
@ITwrx you are missing my point.  Most large organization have a policy to not utilize GPL software period (.) due guidance from legal department and another point was why to start with something that you don't have the intent to support (i understand your point about Microsoft, amazon and google providing massive services and generating revenue without passing it down to the vendor), providing community false pretense is not a good ethics practice. Not trying to get into the argumental discussion but just clarifying so you can understand what the point was.  It was a shock in time and request to consider.  To consider or not to consider is an owner decision.  Thank you for your viewpoint, I agree with most of it if agensgraph initially started under AGPL.  Also, no software is free, to learn an improve software every first invest implementation, testing, and regression testing.  So it is in bitnine's benefit to make it simple to support there core platform component which will allow them to achieve their overarching goal (if they have any, which reading there blog sure seems like there end goal is bigger then agensgraph.  So my feedback was to be strategic which most open source projects are.) which is not limited to agensgraph.   Hope i have done some justice to your input.  Thank you again.

**Comment by gtyun** [comment]
We decided to revert the license commit. 
Thank you for your discussion.

**Comment by johnberzy-bazinga** [comment]
@gtyun Great News! Thanks!

**Comment by pratikpparikh** [comment]
@gtyun Thank you for listening.  Really great news.
