### ISSUE TITLE
BUG: ORDER BY not working correctly with COLLECT

### ISSUE THREAD

**Issue by clery** [bitnine-oss/agensgraph#491]
Let's say I have a database containing people.
What I'd like to do, is to get people, then their siblings, and then their friends to aggregate them as __remote_friends__.

My query looks like this:

```
MATCH (person :person)
WHERE (person.name IN ['Greg', 'Bob', 'Jame'])
OPTIONAL MATCH (person)-[:siblings]->(sibling :person)
OPTIONAL MATCH (sibling)-[:friends]->(friend :person)
WITH person, friend ORDER BY friend.name DESC
RETURN person, COLLECT(properties(friend)) AS remote_friends;
```

So the thing is, the order of the __remote_friends__ array is not "ordered by" `friend.name DESC`.

Although, if I remove the `RETURN` clause, and try something like this:
```
MATCH (person :person)
WHERE (person.name IN ['Greg', 'Bob', 'Jame'])
OPTIONAL MATCH (person)-[:siblings]->(sibling :person)
OPTIONAL MATCH (sibling)-[:friends]->(friend :person)
RETURN person, friend ORDER BY friend.name DESC;
```

The rows are in the expected order. So I can only assume the combination of `ORDER BY` and `COLLECT` does not work as I would expect (or at all, I couldn't say).

If anyone could point me to an alternative (in case this could not be fixed), I'd appreciate that !

**Comment by clery** [comment]
I forgot to mention that I'm running withAgensGraph 2.1.1, based on PostgreSQL 10.4.
It is all running within docker, from the image bitnine/agensbrowser

**Comment by jrgemignani** [comment]
I have reproduced the bug, created a ticket, verified that this is indeed incorrect behaviour and am looking into its cause.

john

**Comment by jrgemignani** [comment]
Okay, for the short answer,... 

This is unfortunately a side effect of using Postgres and unfortunately it wouldn't be easy - or necessarily safe - to fix. It is due to quicksort not being a stable sort.

Okay, for the long answer,...

This bug is due to Postgres's choice of sort algorithms. In this specific case, they use Quicksort, which isn't a stable sort. While stable versions exist, theirs is not one of them. Junseok and I verified this.

To understand what a stable sort is see [https://en.wikipedia.org/wiki/Sorting_algorithm#Stability](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability) To quickly, and roughly, explain it, it means that the order of like keys going into a sort remains the same relative to each other when the sort has completed.

Why is that important to note? Using the following query as an example -

```
# MATCH (p:person)-[:friends]->(f:person)
WITH p, f order by f.name desc
RETURN p as person, COLLECT(f.name) AS friends;
            person            |               friends                
------------------------------+---------------------------------------------
 person[3.2]{"name": "Greg"}  | ["Fred", "Adam"]
 person[3.5]{"name": "Adam"}  | ["Betty", "Fred", "David", "Cathy", "Eric"]
 person[3.6]{"name": "Betty"} | ["Adam", "Cathy", "Bob"]
 person[3.7]{"name": "Cathy"} | ["Adam", "Eric", "David", "Fred"]
(4 rows)
```

In the above query the found friends for each of the persons (Fred, Adam, Betty, Fred, David, Cathy, Eric, Adam, Cathy, Bob, Adam, Eric, David, Fred) are inserted into an array and quick sorted. They are then pulled out of that array, in sorted order (descending, Fred, Fred, Fred, Eric, Eric, etc), paired with their matched person (1 to 1) and then, using the person as the key, inserted into another array for sorting of the person column. 

So that means, 2 entries for Greg, 5 for Adam, 3 for Betty, and 4 for Cathy, in that array - with only the person as the key (fx: **Cathy**-Fred, **Greg**-Fred, **Adam**-Fred, **Cathy**-Eric, **Adam**-Eric, **Cathy**-David, **Adam**-David, **Adam**-Cathy, **Betty**-Cathy, **Betty**-Bob, **Adam**-Betty, **Greg**-Adam, **Betty**-Adam, **Cathy**-Adam) maintaining the descending sort order of the friends. The persons are then quick sorted by their graphid, in this case, grouped together by person, and then returned to the user.

However, while the persons were inserted into the array with their friends - keeping the sort order of the friends - quick sort isn't a stable sort and therefore doesn't preserve the order when sorting using the person as the key. So, the groupings of each person can't guarantee their friends will maintain the original sort of the friends.

This is why the order of the friends isn't sorted for each of the persons in the final output above.
